### Default Pins esp32-devkitC-V4 bzw. Mapping auf IoTKitV3.1 small

DEFAULT_IOTKIT_LED1 = 5
DEFAULT_IOTKIT_BUZZER = 25
DEFAULT_IOTKIT_BUTTON1 = 0

DEFAULT_IOTKIT_I2C_SCL = 4
DEFAULT_IOTKIT_I2C_SDA = 2

DEFAULT_IOTKIT_MOTOR1_FWD	= 12
DEFAULT_IOTKIT_MOTOR1_PWM	= 13
DEFAULT_IOTKIT_MOTOR1_REV	= 14
DEFAULT_IOTKIT_MOTOR2_FWD	= 16
DEFAULT_IOTKIT_MOTOR2_PWM	= 15
DEFAULT_IOTKIT_MOTOR2_REW = 17

DEFAULT_IOTKIT_SPI_SCLK = 23
DEFAULT_IOTKIT_SPI_MISO = 22
DEFAULT_IOTKIT_SPI_MOSI = 21
DEFAULT_IOTKIT_SPI_SS   = 27

DEFAULT_IOTKIT_SERVO1	= 19
DEFAULT_IOTKIT_SERVO2 = 18

DEFAULT_IOTKIT_HALL_SENSOR = 32