### Default Pins esp32-devkitC-V4 bzw. Mapping auf IoTKitV3.1 small

DEFAULT_IOTKIT_LED1 = 5             
DEFAULT_IOTKIT_BUZZER = 26
DEFAULT_IOTKIT_BUTTON1 = 0

# I2C Bus D15 und D14
DEFAULT_IOTKIT_I2C_SCL = 4
DEFAULT_IOTKIT_I2C_SDA = 2

# H-Bridge D2 - D7
DEFAULT_IOTKIT_MOTOR1_FWD	= 12
DEFAULT_IOTKIT_MOTOR1_PWM	= 13
DEFAULT_IOTKIT_MOTOR1_REV	= 14
DEFAULT_IOTKIT_MOTOR2_FWD	= 16
DEFAULT_IOTKIT_MOTOR2_PWM	= 15
DEFAULT_IOTKIT_MOTOR2_REW = 17

# SPI Bus D10 (SS), D11 - D13
DEFAULT_IOTKIT_SPI_SCLK = 23
DEFAULT_IOTKIT_SPI_MISO = 22
DEFAULT_IOTKIT_SPI_MOSI = 21
DEFAULT_IOTKIT_SPI_SS   = 27

# 4 x 3 Header D9 und D8
DEFAULT_IOTKIT_SERVO1 = 19
DEFAULT_IOTKIT_SERVO2 = 18

# Analog Pins, A2 bis A5
DEFAULT_IOTKIT_POTI = 32
DEFAULT_IOTKIT_HALL_SENSOR = 33
DEFAULT_IOTKIT_ADC_4 = 34
DEFAULT_IOTKIT_ADC_5 = 35

# UART
DEFAULT_IOTKIT_UART_TX = 1
DEFAULT_IOTKIT_UART_RX = 3

